### ISSUE TITLE
scatter command

### ISSUE THREAD

**Issue by UnixJunkie** [UnixJunkie/daft#39]

**Comment by UnixJunkie** [comment]
@coti what do you want to do here?
The file will be added locally, then we send each chunk to a different DS in round robin?

**Comment by coti** [comment]
Le 24/06/2015 12:13, Francois Berenger a écrit :
>
> @coti <https://github.com/coti> what do you want to do here?
> The file will be added locally, then we send each chunk to a different 
> DS in round robin?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/UnixJunkie/daft/issues/39#issuecomment-114815055>.
>
> !DSPAM:394,558a82df62631235785479! 
- this is not a scatter command but a parallel scattering strategy for 
the put command
- yes, distributed between the DS in a RR fashion

**Comment by UnixJunkie** [comment]
must be done before the release

**Comment by UnixJunkie** [comment]
I'll attack this feature soon, then we can ship the software and announce it on caml-list at first.

**Comment by UnixJunkie** [comment]
done
