### ISSUE TITLE
Is there any specifications or design docs ?

### ISSUE THREAD

**Issue by AmitKumarDas** [UnixJunkie/daft#87]
Hi,
I have been using ZFS send receive (kernel land) to achieve transferring the change data from one node to another for backup & other purposes.

However, I wanted to learn more on DAFT especially from leaning OCaml w.r.t filesystems.
It will be great if any specs or design docs can be published in this github repository. I am even willing to do the doc side (i.e. markdown effects from plain text material) for DAFT if that helps you.

**Comment by UnixJunkie** [comment]
There is a video about it; the presentation starts
around 6mn40s into the video:
http://www.dailymotion.com/video/x3ihqqa_conf-42-meetup-oups_tech
The slides of this presentation can be seen here:
http://files.meetup.com/6604932/meetup_hiver_2015.zip
That's all the doc there is.

**Comment by AmitKumarDas** [comment]
Thanks.

I had gone through the slides (had got it from the caml-list email group).

I could not understand much of the video due to language issues :(

Thanks again.
